services:
  ffc-pay-statement-constructor:
    build:
      context: .
      target: production
    image: ffc-pay-statement-constructor
    container_name: ffc-pay-statement-constructor
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-statement-constructor-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
