version: '3.8'
services:
  ffc-pay-statement-constructor:
    build:
      context: .
      target: production
    image: ffc-pay-statement-constructor
    container_name: ffc-pay-statement-constructor
    depends_on:
      - ffc-pay-statement-constructor-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-statement-constructor-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      PROCESSING_TOPIC_ADDRESS: ${PROCESSING_TOPIC_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      PROCESSING_SUBSCRIPTION_ADDRESS: ${PROCESSING_SUBSCRIPTION_ADDRESS:-ffc-pay-statement-constructor}${MESSAGE_QUEUE_SUFFIX}
      SUBMIT_TOPIC_ADDRESS: ${SUBMIT_TOPIC_ADDRESS:-ffc-pay-submit}${MESSAGE_QUEUE_SUFFIX}
      SUBMIT_SUBSCRIPTION_ADDRESS: ${SUBMIT_SUBSCRIPTION_ADDRESS:-ffc-pay-statement-constructor}${MESSAGE_QUEUE_SUFFIX}
      RETURN_TOPIC_ADDRESS: ${RETURN_TOPIC_ADDRESS:-ffc-pay-return}${MESSAGE_QUEUE_SUFFIX}
      RETURN_SUBSCRIPTION_ADDRESS: ${RETURN_SUBSCRIPTION_ADDRESS:-ffc-pay-statement-constructor}${MESSAGE_QUEUE_SUFFIX}
      DATA_TOPIC_ADDRESS: ${DATA_TOPIC_ADDRESS:-ffc-pay-statement-data}${MESSAGE_QUEUE_SUFFIX}
      DATA_SUBSCRIPTION_ADDRESS: ${DATA_SUBSCRIPTION_ADDRESS:-ffc-pay-statement-constructor}${MESSAGE_QUEUE_SUFFIX}
      STATEMENT_TOPIC_ADDRESS: ${STATEMENT_TOPIC_ADDRESS:-ffc-pay-statements}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_pay_statement_constructor
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-pay-statement-constructor-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  ffc-pay-statement-constructor-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_pay_statement_constructor
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
