{{- include "ffc-helm-library.container-config-map" (list . "ffc-pay-statement-constructor.config-map") -}}
{{- define "ffc-pay-statement-constructor.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  PROCESSING_TOPIC_ADDRESS: {{ .Values.container.processingTopicAddress }}-{{ .Values.environmentCode }}
  SUBMIT_TOPIC_ADDRESS: {{ .Values.container.submitTopicAddress }}-{{ .Values.environmentCode }}
  RETURN_TOPIC_ADDRESS: {{ .Values.container.returnTopicAddress }}-{{ .Values.environmentCode }}
  DATA_TOPIC_ADDRESS: {{ .Values.container.dataTopicAddress }}-{{ .Values.environmentCode }}
  STATEMENT_TOPIC_ADDRESS: {{ .Values.container.statementTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  PROCESSING_TOPIC_ADDRESS: {{ .Values.container.processingTopicAddress }}
  SUBMIT_TOPIC_ADDRESS: {{ .Values.container.submitTopicAddress }}
  RETURN_TOPIC_ADDRESS: {{ .Values.container.returnTopicAddress }}
  DATA_TOPIC_ADDRESS: {{ .Values.container.dataTopicAddress }}
  STATEMENT_TOPIC_ADDRESS: {{ .Values.container.statementTopicAddress }}
  {{- end }}
  PROCESSING_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.processingSubscriptionAddress }}
  SUBMIT_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.submitSubscriptionAddress }}
  RETURN_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.returnSubscriptionAddress }}
  DATA_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.dataSubscriptionAddress }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_CREATE_CONTAINERS: {{ quote .Values.container.azureStorageCreateContainers }}
  AZURE_STORAGE_CONTAINER: {{ quote .Values.container.storageContainer }}
  AZURE_STORAGE_FOLDER: {{ quote .Values.container.storageFolder }}
  SETTLEMENT_PROCESSING_INTERVAL: {{ quote .Values.container.settlementProcessingInterval }}
  CONSTRUCTION_ACTIVE: {{ quote .Values.container.constructionActive }}
  SCHEDULE_CONSTRUCTION_ACTIVE: {{ quote .Values.container.scheduleConstructionActive }}
  IDLE_CHECK_BATCH_SIZE: {{ quote .Values.container.idleCheckBatchSize }}
  IDLE_CHECK_MAX_DELIVERY_COUNT: {{ quote .Values.container.idleCheckMaxDeliveryCount }}
  IDLE_CHECK_INTERVAL: {{ quote .Values.container.idleCheckInterval }}
  SETTLEMENT_WAIT_TIME: {{ quote .Values.container.settlementWaitTime }}
{{- end -}}
