const {
  ARABLE_LAND: ARABLE_LAND_CODE,
  ARABLE_SOIL: ARABLE_SOIL_CODE,
  HEDGEROW: HEDGEROW_CODE,
  GRASSLAND_SOIL: GRASSLAND_SOIL_CODE,
  GRASSLAND: GRASSLAND_CODE,
  WOODLAND: WOODLAND_CODE,
  LOW_INPUT_GRASSLAND: LOW_INPUT_GRASSLAND_CODE,
  WATER_BODY_BUFFERING: WATER_BODY_BUFFERING_CODE,
  PILOT_PARTICIPATION: PILOT_PARTICIPATION_CODE,
  ARABLE_SOIL_INTRODUCTORY: ARABLE_SOIL_INTRODUCTORY_CODE,
  ARABLE_SOIL_INTERMEDIATE: ARABLE_SOIL_INTERMEDIATE_CODE,
  IMPROVED_GRASSLAND_SOIL_INTRODUCTORY: IMPROVED_GRASSLAND_SOIL_INTRODUCTORY_CODE,
  IMPROVED_GRASSLAND_SOIL_INTERMEDIATE: IMPROVED_GRASSLAND_SOIL_INTERMEDIATE_CODE,
  MOORLAND_INTRODUCTORY: MOORLAND_INTRODUCTORY_CODE,
  MOORLAND_ADDITIONAL: MOORLAND_ADDITIONAL_CODE,
  COMMON_LAND_ADDITIONAL: COMMON_LAND_ADDITIONAL_CODE,
  LUMP_SUM: LUMP_SUM_CODE,
  SHEEP: SHEEP_CODE,
  BEEF_CATTLE: BEEF_CATTLE_CODE,
  DAIRY_CATTLE: DAIRY_CATTLE_CODE,
  PIGS: PIGS_CODE
} = require('./funding-codes')

const {
  ARABLE_LAND,
  ARABLE_SOIL,
  HEDGEROW,
  GRASSLAND_SOIL,
  GRASSLAND,
  WOODLAND,
  LOW_INPUT_GRASSLAND,
  WATER_BODY_BUFFERING,
  PILOT_PARTICIPATION,
  ARABLE_SOIL_INTRODUCTORY,
  ARABLE_SOIL_INTERMEDIATE,
  IMPROVED_GRASSLAND_SOIL_INTRODUCTORY,
  IMPROVED_GRASSLAND_SOIL_INTERMEDIATE,
  MOORLAND_INTRODUCTORY,
  MOORLAND_ADDITIONAL,
  COMMON_LAND_ADDITIONAL,
  LUMP_SUM,
  SHEEP,
  BEEF_CATTLE,
  DAIRY_CATTLE,
  PIGS
} = require('./funding-code-names')

module.exports = [{
  fundingCode: ARABLE_LAND_CODE,
  name: ARABLE_LAND
}, {
  fundingCode: ARABLE_SOIL_CODE,
  name: ARABLE_SOIL
}, {
  fundingCode: HEDGEROW_CODE,
  name: HEDGEROW
}, {
  fundingCode: GRASSLAND_SOIL_CODE,
  name: GRASSLAND_SOIL
}, {
  fundingCode: GRASSLAND_CODE,
  name: GRASSLAND
}, {
  fundingCode: WOODLAND_CODE,
  name: WOODLAND
}, {
  fundingCode: LOW_INPUT_GRASSLAND_CODE,
  name: LOW_INPUT_GRASSLAND
}, {
  fundingCode: WATER_BODY_BUFFERING_CODE,
  name: WATER_BODY_BUFFERING
}, {
  fundingCode: PILOT_PARTICIPATION_CODE,
  name: PILOT_PARTICIPATION
}, {
  fundingCode: ARABLE_SOIL_INTRODUCTORY_CODE,
  name: ARABLE_SOIL_INTRODUCTORY
}, {
  fundingCode: ARABLE_SOIL_INTERMEDIATE_CODE,
  name: ARABLE_SOIL_INTERMEDIATE
}, {
  fundingCode: IMPROVED_GRASSLAND_SOIL_INTRODUCTORY_CODE,
  name: IMPROVED_GRASSLAND_SOIL_INTRODUCTORY
}, {
  fundingCode: IMPROVED_GRASSLAND_SOIL_INTERMEDIATE_CODE,
  name: IMPROVED_GRASSLAND_SOIL_INTERMEDIATE
}, {
  fundingCode: MOORLAND_INTRODUCTORY_CODE,
  name: MOORLAND_INTRODUCTORY
}, {
  fundingCode: MOORLAND_ADDITIONAL_CODE,
  name: MOORLAND_ADDITIONAL
}, {
  fundingCode: COMMON_LAND_ADDITIONAL_CODE,
  name: COMMON_LAND_ADDITIONAL
}, {
  fundingCode: LUMP_SUM_CODE,
  name: LUMP_SUM
}, {
  fundingCode: SHEEP_CODE,
  name: SHEEP
}, {
  fundingCode: BEEF_CATTLE_CODE,
  name: BEEF_CATTLE
}, {
  fundingCode: DAIRY_CATTLE_CODE,
  name: DAIRY_CATTLE
}, {
  fundingCode: PIGS_CODE,
  name: PIGS
}]
