environment: development
environmentCode:
name: ffc-pay-statement-constructor
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-statement-constructor

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-statement-constructor-config-map

containerSecret:
  name: ffc-pay-statement-constructor-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: Always
  requestMemory: 150Mi
  requestCpu: 120m
  limitMemory: 150Mi
  limitCpu: 180m
  messageQueueHost: namespace.servicebus.windows.net
  processingTopicAddress: ffc-pay-processing
  processingSubscriptionAddress: ffc-pay-ffc-pay-statement-constructor
  submitTopicAddress: ffc-pay-submit
  submitSubscriptionAddress: ffc-pay-ffc-pay-statement-constructor
  returnTopicAddress: ffc-pay-return
  returnSubscriptionAddress: ffc-pay-ffc-pay-statement-constructor
  statementTopicAddress: ffc-pay-statements
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: statements
  storageFolder: inbound

postgresService:
  postgresDb: ffc_pay_statement_constructor
  postgresqlHost: ffc-pay-statement-constructor-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
